---
# Common software prerequisites for DC/OS 1.9

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Install prerequisite packages for DC/OS
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - tar
    - xz
    - unzip
    - curl
    - ipset

# Disable firewalld due to issue with Docker
# Suitable for test/dev environments only

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

# Everything needed for DC/OS supported version of Docker
# No need to set storage driver to OverlayFS. Set by default in Docker 1.13

- name: Add Docker yum repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    file: docker

- name: Install Docker Engine
  yum:
    name: docker-engine-1.13.1
    update_cache: yes

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker

- name: Start Docker service
  service:
    name: docker
    enabled: yes
    state: started

# Create an install directory to keep everything tidy

- name: Create install directory
  file:
    path: ~/dcos
    state: directory