---
- hosts: dcos-all
  become: true
  roles:
  - dcos-common

- hosts: dcos-bootstrap
  become: true
  roles:
  - dcos-bootstrap

- hosts: dcos-masters
  become: true
  roles:
  - dcos-masters

- hosts: dcos-priv-agents
  become: true
  roles:
  - dcos-priv-agents

- hosts: dcos-pub-agents
  become: true
  roles:
  - dcos-pub-agents
